### ISSUE TITLE
Enviroment packages and version

### ISSUE THREAD

**Issue by ZiRanSlash** [songtaohe/LaneExtraction#4]
Hi,

I had some problem when I run this code because package's version is incorrect, such as Tensorflow, Scipy.

Could you please provide an environment packages and version list to ensure that I can create a correct environment?

Thank you so much!

**Comment by GoroYeh-HRI** [comment]
I got this error when executing `python train.py resnet34v3`

![image](https://github.com/songtaohe/LaneExtraction/assets/137837175/ef0a0a08-a6c2-4936-9389-a09c1f9597ed)


Could someone help me with the package version and requirements?
Thank you!
